# Generated by Django 3.2.5 on 2021-07-11 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('icon', models.ImageField(default='sector.png', upload_to='sector')),
                ('slug', models.SlugField(default='GSE', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=10)),
                ('logo', models.ImageField(default='sector.png', upload_to='company')),
                ('isin', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('postal_address', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_office', models.CharField(blank=True, max_length=50, null=True)),
                ('incorporated_date', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('toll_free', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('core_activities', models.TextField()),
                ('industry', models.ManyToManyField(blank=True, related_name='tags', to='core.Tag')),
                ('market', models.ManyToManyField(default='GSE', related_name='tags', to='core.Market')),
                ('sector', models.ManyToManyField(blank=True, related_name='tags', to='core.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='ChiefExecutiveOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('appointed_date', models.DateField()),
                ('company', models.ManyToManyField(to='core.CompanyProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('appointed_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
