# Generated by Django 3.2.5 on 2021-07-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chairman_chiefexecutiveofficer_companyprofile_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_shares', models.PositiveBigIntegerField()),
                ('stated_capital', models.PositiveBigIntegerField(blank=True, null=True)),
                ('listed_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile')),
            ],
        ),
    ]
