# Generated by Django 3.2.5 on 2021-07-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shareprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
