# Generated by Django 3.2.5 on 2021-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indices',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
