# Generated by Django 3.2.5 on 2021-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_companyprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='reports')),
                ('session_number', models.PositiveIntegerField()),
            ],
        ),
    ]
