# Generated by Django 3.2.5 on 2021-07-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_no', models.PositiveIntegerField(default=1)),
                ('dates', models.CharField(max_length=120)),
                ('effective_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
