# Generated by Django 3.2.5 on 2021-07-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_mpr'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_BILL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('tender', models.PositiveIntegerField()),
                ('security', models.CharField(max_length=120)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
