# Generated by Django 3.2.5 on 2021-07-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_t_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('91 DAY BILL', '91 DAY BILL'), ('182 DAY BILL', '182 DAY BILL'), ('364 DAY BILL', '364 DAY BILL'), ('1 YR FXR BOND', '1 YR FXR BOND'), ('2 YR FXR BOND', '2 YR FXR BOND'), ('3 YR FXR BOND', '3 YR FXR BOND'), ('5 YR FXR BOND', '5 YR FXR BOND'), ('6 YR FXR BOND', '6 YR FXR BOND'), ('7 YR FXR BOND', '7 YR FXR BOND'), ('10 YR FXR BOND', '10 YR FXR BOND'), ('15 YR FXR BOND', '15 YR FXR BOND'), ('20 YR FXR BOND', '20 YR FXR BOND')], max_length=50)),
                ('slug', models.SlugField(default='ash', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='t_bill',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.security'),
        ),
    ]
