# Generated by Django 3.2.5 on 2021-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20210711_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='region',
            new_name='security',
        ),
        migrations.AlterField(
            model_name='security',
            name='slug',
            field=models.SlugField(default='91 DAY BILL', unique=True),
        ),
    ]
