# Generated by Django 3.2.5 on 2021-07-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_auto_20210711_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='slug',
            field=models.SlugField(default='91_DAY_BILL', unique=True),
        ),
    ]
